refactor: introduce possibility to observe host for named slot changes
lyne-design-system/lyne-components pull request #1375
Opened 2022-09-14 06:30 UTC by kyubisation

We have various use cases where we want to remove or render an entire section of elements, depending on whether a specific element is slotted into a named slot.
This PR introduces functionality to define a named slot state and a way to observe the light DOM of the host for changes.

2022-09-14 10:47 UTC, DavideMininni-Fincons reviewed
It looks great. 🚀 
Question: we can't test it until the Stencil slotchange bug is fixed, right?

2022-09-14 13:18 UTC, jeripeierSBB commented
> It looks great. 🚀 Question: we can't test it until the Stencil slotchange bug is fixed, right?

Maybe with an e2e test?

2022-09-19 16:50 UTC, jeripeierSBB requested changes
Generaly looks super :)

should we add documentation in this Pr?

2022-09-21 12:04 UTC, jeripeierSBB commented
Reminder: Please use logic in sbb-link-list

2022-09-21 12:35 UTC, kyubisation commented on src/global/helpers/observe-named-slot-changes.ts
> +      host.dispatchEvent(new CustomEvent('sbbSlotNameChange', { detail: slotNames }));
Better name for event and utility functions

2022-09-23 15:49 UTC, kyubisation commented on src/components/sbb-form-field/sbb-form-field.tsx
> +                    <span aria-hidden="true">&nbsp;{i18nOptional[this._currentLanguage]}</span>
Good question. Technically a form element can declare itself, whether it is required or not (via required attribute).

2022-09-29 12:23 UTC, merged