refactor(sbb-menu): improve menu events and positioning
lyne-design-system/lyne-components pull request #1430
Opened 2022-10-26 13:38 UTC by dauriamarco

Improved handling of window-related events, improved positioning function, and extracted logic for focus trapping.

2022-10-27 18:09 UTC, kyubisation requested changes
I like the general direction, but have a few thoughts

2022-11-01 10:19 UTC, jeripeierSBB submitted a review, later dismissed

2022-11-01 10:19 UTC, jeripeierSBB commented on src/global/helpers/position.ts
> +export type Alignment = { horizontal: 'start' | 'center' | 'end'; vertical: 'above' | 'below' };
Can you change that to an interface?
```suggestion
export interface Alignment = { horizontal: 'start' | 'center' | 'end'; vertical: 'above' | 'below' };
```

2022-11-01 10:19 UTC, jeripeierSBB commented on src/global/helpers/position.ts
>  export function getElementPosition(
What about unit testing? It has quite a bit of logic in this file :)

2022-11-01 10:19 UTC, jeripeierSBB commented on src/components/sbb-menu/sbb-menu.scss
> +      max-height: max(120px, var(--sbb-menu-max-height));
I preferred the solution where 120px was in the var `-sbb-menu-min-height: #{px-to-rem-build(120)};`.
What is the reason you removed it?

2022-11-01 10:19 UTC, jeripeierSBB commented on src/components/sbb-menu/sbb-menu.scss
> +  max-height: calc(90vh - var(--sbb-spacing-fixed-8x));
the value `calc(90vh - var(--sbb-spacing-fixed-8x))` is duplicated now, please use a var

2022-11-02 13:13 UTC, jeripeierSBB commented on src/global/helpers/focus.ts
> +/**
Probably wrong comment?

2022-11-03 11:55 UTC, dauriamarco commented on src/global/helpers/focus.ts
> +export function trapFocus(
Sounds good to me 👍

2022-11-03 17:04 UTC, kyubisation requested changes
One issue and some suggestions

2022-11-03 17:04 UTC, kyubisation commented on src/global/helpers/focus.ts
> +        }
Nitpick
```suggestion
        const [pivot, next] = event.shiftKey
          ? [firstFocusable, lastFocusable]
          : [lastFocusable, firstFocusable];
        if (element.shadowRoot.activeElement === pivot || document.activeElement === pivot) {
          next.focus();
          event.preventDefault();
        }
```

2022-11-04 14:20 UTC, kyubisation approved these changes
LGTM 👍 
Thank you very much!

2022-11-04 14:26 UTC, merged