refactor: interface and markup trip
lyne-design-system/lyne-components pull request #1440
Opened 2022-10-31 07:26 UTC by osminaz

## Preflight Checklist

- [ x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

In order to use this component with our API some changes had to be done

2022-10-31 08:13 UTC, jeripeierSBB requested changes

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
> +        {this.departureWalk > 0 ? (
```suggestion
        {this.departureWalk > 0 && (
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
> +        {this.arrivalWalk > 0 ? (
```suggestion
        {this.arrivalWalk > 0 && (
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
> +          ''
```suggestion
        )
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
> +          ''
```suggestion
        )
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> +   * example: Your connecting train will be waiting, please change trains immediately.
```suggestion
   * Example: Your connecting train will be waiting, please change trains immediately.
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> + * A passenger carrying Service (phyisical public transport vehicle)
```suggestion
 * A passenger carrying Service (physical public transport vehicle)
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> + * provided and operated by a certain Operator allocated to a concrete ServiceJourney
```suggestion
 * provided and operated by a certain operator allocated to a concrete ServiceJourney
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> +   */
Can Todo be avoided? And please in English language.

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> +   */
```suggestion
  /**
   * Unique per OperatingDay and name (where 'IC 1' can run several times per day in either of opposite directions).
   * Example: 753
   */
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-pearl-chain/sbb-pearl-chain.custom.d.ts
> +   * example: IC
```suggestion
   * Example: IC
```

2022-10-31 08:13 UTC, jeripeierSBB commented on src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
> +export const convertCauseInIconName = (cause: PtSituationCauseEnum): string => {
I'm not sure whether this should be done in lyne. But all the pearl chain is very near to your backend API, so maybe it's ok for the moment. @kyubisation ?

2022-11-01 07:50 UTC, osminaz commented on src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
> +  @Prop() public departureWalk?: any;
Currently the generated types contains in some places the type any, Im sure that we will change it in future. I will add a comment to it for now

2022-11-01 13:26 UTC, jeripeierSBB approved these changes
LGTM

 - Please rebase
 - Please call me to go through chromatic issues (after rebasing)

2022-11-01 15:19 UTC, merged