feat(sbb-navigation): introduce first-level navigation component
lyne-design-system/lyne-components pull request #1480
Opened 2022-12-02 10:22 UTC by dauriamarco

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1173

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- implement `sbb-navigation` component (first-level)
- implement `sbb-navigation-marker` and `sbb-navigation-list`

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [x] Chrome Mobile
- [x] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [x] VoiceOver Safari Desktop
- [x] VoiceOver Chrome Desktop
- [x] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-12-20 14:13 UTC, jeripeierSBB requested changes
Overall, very nice work! Some questions open to me

2022-12-20 14:13 UTC, jeripeierSBB commented on src/components/sbb-navigation-section/sbb-navigation-section.tsx
> +          [`sbb-navigation-section--${this._state}`]: true,
also comparing to sbb-navigation I suggest to use the implementation made there

2022-12-20 14:13 UTC, jeripeierSBB commented on src/components/sbb-navigation-section/sbb-navigation-section.e2e.ts
> +import { E2EElement, E2EPage, newE2EPage } from '@stencil/core/testing';
please add some tests

2022-12-20 14:13 UTC, jeripeierSBB commented on src/components/sbb-navigation-section/sbb-navigation-section.scss
> +  ::slotted(*) {
why does it have to be on the slotted content?

2022-12-20 14:13 UTC, jeripeierSBB commented on src/components/sbb-navigation-section/sbb-navigation-section.scss
> +  display: none;
Also here, discussion about whether to apply styles on the host

2022-12-20 14:18 UTC, MarioCastigliano commented on src/components/sbb-navigation-list/sbb-navigation-list.tsx
> +  /*
There are no size variants in the sbb-navigation-list, as it's always 'm'

2022-12-20 14:29 UTC, jeripeierSBB commented on src/components/sbb-navigation-list/sbb-navigation-list.tsx
> +  /*
yes, but we could force sizing to children?

2022-12-20 14:40 UTC, jeripeierSBB commented on src/components/sbb-navigation-marker/sbb-navigation-marker.scss
> +:host {
maybe recheck, but leave it as it is

2022-12-20 14:41 UTC, jeripeierSBB commented on src/components/sbb-navigation-marker/sbb-navigation-marker.scss
> +:host {
comment where it's not possible to move into the component

2022-12-20 14:51 UTC, jeripeierSBB commented on src/components/sbb-navigation-list/sbb-navigation-list.tsx
> +  /*
don't forget to update stories and docs everywhere

2022-12-20 15:31 UTC, jeripeierSBB commented on src/components/sbb-navigation-section/sbb-navigation-section.scss
> +  ::slotted(*) {
maybe try styling the slot

2022-12-21 13:50 UTC, MarioCastigliano commented on src/components/sbb-navigation-section/sbb-navigation-section.tsx
> +    if (isBreakpoint('zero', 'large')) {
Because you should never be able to see the marker on mobile or smaller breakpoints (up to medium)

2022-12-22 17:04 UTC, jeripeierSBB requested changes

2022-12-22 17:04 UTC, jeripeierSBB commented on src/storybook/pages/home/home--logged-in.stories.js
> +          <sbb-navigation-action size="m">Label</sbb-navigation-action>
remove size m for alllllll lines :D

2022-12-22 17:04 UTC, jeripeierSBB commented on src/storybook/pages/home/home.stories.js
> +          <sbb-navigation-action size="m">Label</sbb-navigation-action>
size m removeeeeee

2022-12-22 17:37 UTC, jeripeierSBB approved these changes
LGTM, thanks for the great work!

2022-12-23 13:20 UTC, merged