Id references not working
lyne-design-system/lyne-components pull request #1493
Opened 2022-12-12 13:42 UTC by simone-sabato

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-12-13 08:09 UTC, dauriamarco commented on src/components/sbb-dialog/sbb-dialog.tsx
> -          aria-labelledby={this.accessibilityLabelledby || this.titleId}
Sure, I'll do some quick tests to see if it works

2022-12-13 11:39 UTC, jeripeierSBB commented on src/components/sbb-dialog/sbb-dialog.tsx
> -          aria-labelledby={this.accessibilityLabelledby || this.titleId}
I tested with an <ul> arialabelledby to a sbb-title, and it worked, so I guess this scenario should also work

2022-12-13 11:43 UTC, jeripeierSBB requested changes

2022-12-13 11:43 UTC, jeripeierSBB commented on src/components/sbb-tooltip/readme.md
> -<button id="tooltip-trigger" aria-describedby="tooltip-content">Button with tooltip</button>
this change should be reverted too

2022-12-13 12:12 UTC, dauriamarco commented on src/components/sbb-dialog/sbb-dialog.tsx
> -          aria-labelledby={this.accessibilityLabelledby || this.titleId}
From my first tests it seems not to work on the dialog with aria-labelledby but only with aria-label, strange but to be investigated further

2022-12-15 07:16 UTC, jeripeierSBB requested changes
in general: accessibility-controls attribute in button interface can be removed and refactored away (it does not work)

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-radio-button/sbb-radio-button.tsx
> +  private _radioButtonLabelId = 'sbb-radio-button-label-id';
It doesn't seem that there is any use case for this id, so please remove it.

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-radio-button/sbb-radio-button.tsx
> +        <label id={this._radioButtonLabelId} htmlFor={this._radioButtonId} class="sbb-radio-button">
As the label is wrapped around the input, you don't need _radioButtonId anymore (sorry wrong advice of me before.)

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-teaser/sbb-teaser.e2e.ts
> -
Here we should find another solution to make the test running

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-toggle-check/readme.md
> +
```suggestion

```

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-tooltip/readme.md
> +<button id="tooltip-trigger" aria-describedby="tooltip-content">Button with tooltip</button>
please revert this changes

2022-12-15 07:16 UTC, jeripeierSBB commented on src/components/sbb-dialog/sbb-dialog.tsx
> +        accessibility-controls={this._dialogId}
this will not work, but you can try the following and check with screenreader
```suggestion
        aria-controls={this._dialogId}
```

2022-12-15 13:22 UTC, jeripeierSBB approved these changes
LGTM

2022-12-15 13:29 UTC, merged