feat(sbb-journey-header): component refactoring
lyne-design-system/lyne-components pull request #1539
Opened 2023-01-17 13:49 UTC by DavideMininni-Fincons

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1240 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- component refactoring

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [x] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): component refactoring

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

- `appearance` prop has been removed;
- `isRoundTrip` prop has been renamed to `roundTrip`;
- `markup` prop has been renamed to `level` and values has been changed;
- `negative` prop has been added;
- `size` has now `m` and `l` as values instead of `5` and `4`.

## Other information

2023-01-19 08:34 UTC, jeripeierSBB requested changes
Thanks for the refactoring! Some open issues.

- home logged in story has to be migrated (usage of journey header 2x)
- sbb-card-product.stories.js has to be migrated (usage of journey header)

2023-01-20 14:48 UTC, DavideMininni-Fincons commented on src/components/sbb-journey-header/sbb-journey-header.scss
> +.sbb-journey-header[id] {
It works, so I changed it as suggested 🚀

2023-01-20 16:39 UTC, kyubisation approved these changes
LGTM 👍

2023-01-23 07:31 UTC, jeripeierSBB requested changes
Almost done ;)

Some comments regarding the sbb-title refactoring and the chromatic stories fiel is missing. Please add it.

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.custom.d.ts
> +  level: '1' | '2' | '3' | '4' | '5' | '6';
please remove here and in tsx file import directly from title `InterfaceTitleAttributes['level']`
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
>    --sbb-title-text-color-normal: var(--sbb-color-charcoal-default);
It's handled in sbb-title.
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
> +}
It's defined in sbb-title
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
> +  --sbb-title-margin-block-end: 0;
It's easier like that and also consistent with other cases in code base.
```suggestion
  // Overwrite sbb-title default margin
  margin: 0;
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
> +  @include sbb.title-5($exclude-spacing: true);
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
> +  }
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.scss
>    color: var(--sbb-title-text-color-normal);
```suggestion
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.tsx
> +  @Prop() public level?: InterfaceJourneyHeaderAttributes['level'] = '3';
```suggestion
  @Prop() public level?: InterfaceTitleAttributes['level'] = '3';
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.tsx
> +   * it is important to pick the correct markup element to match the correct semantics.
```suggestion
   * Heading level of the journey header element (e.g. h1-h6).
```

2023-01-23 07:31 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.tsx
> +      <sbb-title level={this.level} negative={this.negative}>
You need to transform the size property into the visualLevel property of the sbb-title. I don't know the actual sizes but something like 
```suggestion
      <sbb-title level={this.level} negative={this.negative} visual-level={this.size === 'm' ? '5' : '3'}>
```

2023-01-23 09:13 UTC, jeripeierSBB commented on src/components/sbb-journey-header/sbb-journey-header.tsx
> +      <sbb-title level={this.level} negative={this.negative} visual-level={this.size === 'l' ? '3' : '5'}>
Is it not level 4?
```suggestion
      <sbb-title level={this.level} negative={this.negative} visual-level={this.size === 'l' ? '3' : '4'}>
```

2023-01-23 11:06 UTC, jeripeierSBB approved these changes
LGTM, thanks

2023-01-23 12:03 UTC, merged