feat(sbb-clock): component refactoring
lyne-design-system/lyne-components pull request #1567
Opened 2023-01-25 14:01 UTC by DavideMininni-Fincons

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-01-25 14:05 UTC, jeripeierSBB requested changes
you need to update footer and home stories with the data-now attribute

2023-01-25 14:05 UTC, jeripeierSBB commented on src/components/sbb-clock/sbb-clock.stories.js
> +Paused.args = { 'data-now': 1677273030000 };
I'd prefer the approach like you did on line 33

2023-01-25 14:06 UTC, jeripeierSBB commented on src/components/sbb-clock/sbb-clock.stories.js
> +    type: 'number',
I think you can use the same approach as in other components where you can chose a date (date control or similar)

2023-01-30 07:55 UTC, kyubisation approved these changes
LGTM 👍 
Excellent work!

2023-01-30 07:55 UTC, kyubisation commented on src/components/sbb-clock/sbb-clock.tsx
>    private _getCurrentTime(): void {
Nitpick; This does not actually get the current time, but assign the current time. Should this maybe be renamed to `_assignCurrentTime`?

2023-01-30 07:55 UTC, kyubisation commented on src/components/sbb-clock/sbb-clock.tsx
> +      this._addMinutesAndSetHands.bind(this),
Nitpick; I generally prefer `() => this.method()` to `this.method.bind(this)` as it is easier to find in my mind.
What do you think?

2023-01-30 08:12 UTC, jeripeierSBB requested changes
Sadly, the iOS bug still exists

2023-01-30 08:12 UTC, jeripeierSBB commented on src/components/sbb-clock/sbb-clock.stories.js
> +    'data-now': new Date('2023-01-24T10:10:30+01:00').valueOf(),
I see that the clock is displayed with 09:10:30. I guess it's coming from the +01:00 timezone.  But the question is, in which timezone should the clock be shown? As it's only for testing, this is not a big question, but I'm insecure wether the current approach is the best?

2023-01-30 08:33 UTC, jeripeierSBB commented on src/components/sbb-clock/sbb-clock.stories.js
> +    'data-now': new Date('2023-01-24T10:10:30+01:00').valueOf(),
It's only chromatic. All is ok

2023-01-30 09:24 UTC, DavideMininni-Fincons commented
> Sadly, the iOS bug still exists

@jeripeierSBB is there a way to replicate this? Tried again this morning in Safari, both Mac and iPhone, and it seems to work, I've tried app switching, rotating, waiting for minute change, and so on.. It only looks a bit 'slower' on iPhone, but maybe it's just a feeling

2023-01-30 09:28 UTC, jeripeierSBB commented
> > Sadly, the iOS bug still exists
> 
> @jeripeierSBB is there a way to replicate this? Tried again this morning in Safari, both Mac and iPhone, and it seems to work, I've tried app switching, rotating, waiting for minute change, and so on.. It only looks a bit 'slower' on iPhone, but maybe it's just a feeling

I'll have a look at it. I took the home story in portrait mode, changed to landscape mode and back to portrait mode and then clock hands were misplaced all the time. (iPhone 13, newest iOS)

2023-01-31 09:08 UTC, jeripeierSBB approved these changes
LGTM, thanks!

2023-01-31 10:47 UTC, merged