fix(sbb-header): missing icon and text translate on hover
lyne-design-system/lyne-components pull request #1585
Opened 2023-01-31 09:37 UTC by federicoisepponfincons

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes the bug reported by Florian, about missing animation on hover of header action elements
https://github.com/lyne-design-system/lyne-components/issues/1569

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- added translation to text and icon, when header action is hovered

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-01-31 10:20 UTC, jeripeierSBB requested changes
I asked Florian for a UX review. It can be that on active, the shift should be reset. But wait for the answer.

2023-01-31 10:20 UTC, jeripeierSBB commented on src/components/sbb-header-action/sbb-header-action.scss
> +    --sbb-header-action-translate: #{sbb.px-to-rem-build(-1)};
I know it's not necessary, but I'd suggest to initialize --sbb-header-action-translate-y with 0 on :host{}.

2023-01-31 10:20 UTC, jeripeierSBB commented on src/components/sbb-header-action/sbb-header-action.scss
> +  color: var(--sbb-color-black-default);
setting the color could also work by adding to .sbb-header-action (inherited)

2023-01-31 10:20 UTC, jeripeierSBB commented on src/components/sbb-header-action/sbb-header-action.scss
> +    --sbb-header-action-translate: #{sbb.px-to-rem-build(-1)};
```suggestion
    --sbb-header-action-translate-y: #{sbb.px-to-rem-build(-1)};
```

2023-01-31 11:26 UTC, jeripeierSBB commented
> I asked Florian for a UX review. It can be that on active, the shift should be reset. But wait for the answer.

@federicoisepponfincons after discussion with florian: on active state, the shift should be reset.

2023-02-01 07:51 UTC, federicoisepponfincons commented
@jeripeierSBB allright, the shifting should be only on the hover state and not on the active one

2023-02-01 16:57 UTC, kyubisation approved these changes
LGTM 👍

2023-02-06 08:48 UTC, jeripeierSBB requested changes

2023-02-06 08:48 UTC, jeripeierSBB commented on src/components/sbb-header-action/sbb-header-action.scss
>    &:focus-visible {
focus-visible state is broken. I think it should also be applied to the ::before (?)

2023-02-06 08:48 UTC, jeripeierSBB commented on src/components/sbb-header-action/sbb-header-action.scss
> +    border-radius: var(--sbb-border-radius-16x);
I suggest to use the height as it is a little bit less just a fantasy value.
```suggestion
    border-radius: var(--sbb-header-action-min-height);
```

2023-02-06 09:00 UTC, jeripeierSBB requested changes
I just realized, that on windows high contrast mode, the header hover doesn't look like other hover effects (e.g. button).

2023-02-08 10:46 UTC, federicoisepponfincons commented
@jeripeierSBB added the high contrast effect (as seen in the button component) and fixed the hover / active animation

2023-02-09 10:15 UTC, jeripeierSBB approved these changes
LGTM, thanks!

2023-02-09 10:25 UTC, merged