fix(sbb-header): prevent unwanted hiding and use transform for the animation
lyne-design-system/lyne-components pull request #1621
Opened 2023-02-14 09:05 UTC by dauriamarco

Prevent the header from being hidden when the navigation is open/closed. Use the CSS `translateY` to perform the animation, instead of using `inset-block-start`.

2023-02-14 09:17 UTC, jeripeierSBB requested changes

2023-02-14 09:17 UTC, jeripeierSBB commented on src/global/helpers/scroll.ts
> +    toggleDatasetEntry(document.body, 'scrollDisabled', true);
As it is on a non lyne component, we should probably prefix with "sbb"

2023-02-15 11:14 UTC, jeripeierSBB requested changes

2023-02-15 11:14 UTC, jeripeierSBB commented on src/components/sbb-header/sbb-header.scss
> +    property: var(--sbb-header-transition-property);
I think we should remove the var(--sbb-header-transition-property) and inline it

2023-02-15 11:14 UTC, jeripeierSBB commented on src/components/sbb-header/sbb-header.scss
> +  }
What about introducing css vars and toggle the vars on host level where all other vars are toggled?

2023-02-15 11:14 UTC, jeripeierSBB commented on src/components/sbb-header/sbb-header.tsx
> +  private _getScrollDocumentElement(): HTMLElement {
I suggest to use this method in _getCurrentScroll() as well

2023-02-20 10:57 UTC, dauriamarco commented on src/components/sbb-header/sbb-header.tsx
> +    if (currentScroll > this._element.offsetHeight * 2) {
You're right, I didn't ask him. I'll write to him as soon as he's available 👍

2023-02-20 15:45 UTC, dauriamarco commented on src/components/sbb-menu/sbb-menu.tsx
> -    if (!isBreakpoint('medium') || !this._dialog || !this._triggerElement) {
I'm not sure if it's possible to replicate the same scenario where the menu is being closed and at the same time the trigger changes position and check everything with the correct timing.

2023-02-21 09:07 UTC, dauriamarco commented on src/components/sbb-header/sbb-header.tsx
> +    if (
Despite the changes, the behaviour remains more or less the same. Apart from the new point where the header becomes fixed (header height * 2) which has to be confirmed by Manuel and the bouncing on mobile which I don't know how to replicate, but I can try something. Do you have any more suggestions on how to improve them?

2023-02-21 10:25 UTC, jeripeierSBB commented on src/components/sbb-header/sbb-header.tsx
> +    toggleDatasetEntry(this._element, 'shadow', currentScroll !== 0 || pageScrollDisabled());
```suggestion
    toggleDatasetEntry(this._element, 'shadow', currentScroll !== 0);
```

2023-02-21 10:26 UTC, jeripeierSBB approved these changes
LGTM

2023-02-21 11:35 UTC, merged