feat: add additional prop to display roundtrip
lyne-design-system/lyne-components pull request #1761
Opened 2023-05-22 13:30 UTC by k-luise

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x ] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- added additional prop and capabilites to display a roundtrip

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-05-22 14:18 UTC, WalkingOS requested changes

2023-05-30 08:06 UTC, jeripeierSBB commented on src/components/sbb-journey-summary/readme.md
> +The Example below shows how to render the component with a button in the slot. To be displayed correctly, the trip prop has to include almost all probierties mentioned in the table below. It is impor
```suggestion
The Example below shows how to render the component with a button in the slot. To be displayed correctly, the trip prop has to include almost all properties mentioned in the table below. It is important that the arrival and departure properties consist of an valid ISO 8601 date string. If this is not the case, the times and the date will not be displayed. If the tripBack prop is passed to the component, a second journey-summary, without the header, is displayed.
```

2023-05-30 08:12 UTC, jeripeierSBB commented on src/components/sbb-journey-summary/sbb-journey-summary.tsx
> +  @Prop() public roundTrip?: boolean;
Docs missing

2023-05-30 08:16 UTC, jeripeierSBB commented on src/components/sbb-journey-summary/sbb-journey-summary.stories.jsx
>  );
"TemplateRoundtrip" can probably removed and replaced by the simplified "TemplateNoSlot"

2023-05-30 14:03 UTC, jeripeierSBB approved these changes

2023-05-30 14:04 UTC, merged