feat(sbb-datepicker): improve datepicker
lyne-design-system/lyne-components pull request #1763
Opened 2023-05-23 08:12 UTC by MarioCastigliano

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes [#1753](https://github.com/lyne-design-system/lyne-components/issues/1753)

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

-

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [x] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-05-23 13:33 UTC, DavideMininni-Fincons commented on src/components/sbb-datepicker/sbb-datepicker.tsx
> +    }
The difference between the two is just the _+_ in the `new Date()`, right? Maybe a method can be extracted?

2023-05-24 06:23 UTC, jeripeierSBB requested changes

2023-05-24 06:23 UTC, jeripeierSBB commented on src/components/sbb-datepicker/sbb-datepicker.tsx
> +    if (!Number.isNaN(+value) && Number.isInteger(+value)) {
I think this check is enough as NaN is not an Integer?
```suggestion
    if (Number.isInteger(+value)) {
```

2023-05-24 06:23 UTC, jeripeierSBB commented on src/components/sbb-datepicker/sbb-datepicker.tsx
> +    if (match && match?.index === 0) {
```suggestion
    if (match?.index === 0) {
```

2023-05-24 08:10 UTC, kyubisation approved these changes
Generally looks good to me, thank you for your work 👍 
One thing I am not sure about is server side rendering; If the date is passed as an ISO string, is it reformated quickly enough when transitioning to the client or would the client see the ISO string, before it is reformated.

2023-05-24 08:10 UTC, kyubisation commented on src/components/sbb-datepicker/sbb-datepicker.tsx
> +      this._inputElement.value = this._getValidValue(this._inputElement?.value);
```suggestion
      this._inputElement.value = this._getValidValue(this._inputElement.value);
```

2023-05-24 08:10 UTC, kyubisation commented on src/components/sbb-datepicker/sbb-datepicker.tsx
> +    if (Number.isInteger(+value)) {
Nitpick
```suggestion
    } else if (Number.isInteger(+value)) {
```

2023-05-24 08:50 UTC, kyubisation approved these changes
LGTM 👍 
Thank you very much!

2023-05-24 09:33 UTC, jeripeierSBB approved these changes
LGTM

2023-05-24 14:49 UTC, merged