feat(sbb-no.results): first implementation
lyne-design-system/lyne-components pull request #1943
Opened 2023-08-22 08:05 UTC by MarioCastigliano

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1927 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- Implement sbb-no-results component

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [x] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [x] VoiceOver Safari Desktop
- [x] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [x] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-22 10:28 UTC, dauriamarco requested changes
Hi and thanks a lot! Just few comments below :)

2023-08-22 10:28 UTC, dauriamarco commented on src/components/sbb-no-results/sbb-no-results.tsx
> +        <slot name="title">
Sorry, I didn't notice before when we discussed it but the title logic should probably need to be adapted to the other similar implementations where we have the title slot inside the `sbb-title` itself (see `sbb-alert`and the `.sbb-alert__title` element for reference).

2023-08-22 10:28 UTC, dauriamarco commented on src/components/sbb-no-results/sbb-no-results.scss
> +  display: flex;
Is the `display: flex` really needed? The `text-align: center` might be sufficient (?). And would it be possible to move the styles from the host to an inner container for consistency/stability? What do you think?

```scss
 .sbb-no-results__container {
  text-align: center;
}
```

2023-08-22 10:28 UTC, dauriamarco commented on src/components/sbb-no-results/sbb-no-results.scss
> +sbb-title,
See comment about the title logic in `.tsx`

2023-08-22 10:28 UTC, dauriamarco commented on src/components/sbb-no-results/readme.md
> +By default the `sbb-title` has a visual level of 5 and an actual level of 3. This can be changed by the user either via the `title-level` property, or via slotting an `sbb-title` in the `title` slot,
See comment about the title logic in `.tsx`.

2023-08-22 10:51 UTC, dauriamarco requested changes

2023-08-22 10:51 UTC, dauriamarco commented on src/components/sbb-no-results/sbb-no-results.tsx
> +          <sbb-title level={this.titleLevel} visualLevel="5">
```suggestion
          <sbb-title level={this.titleLevel} visualLevel="5" class="sbb-no-results__title">
```

2023-08-22 10:51 UTC, dauriamarco commented on src/components/sbb-no-results/sbb-no-results.scss
> +}
To fix the title margin:
```suggestion
.sbb-no-results__title {
  // Overwrite sbb-title default margin
  margin: 0;
}
```

2023-08-22 11:31 UTC, dauriamarco approved these changes
LGTM 👍
We can wait for the UI review by @mcilurzo: https://lyne-components-preview-pr1943.app.sbb.ch/?path=/story/components-sbb-no-results--default

2023-08-27 08:43 UTC, mcilurzo commented
ux-review: i found one small issue: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj?node-id=26906:46319&mode=design#538204670

2023-08-28 07:55 UTC, MarioCastigliano commented
@mcilurzo fixed, let me know if you find anything else https://lyne-components-preview-pr1943.app.sbb.ch/?path=/story/components-sbb-no-results--default

2023-08-28 07:57 UTC, mcilurzo commented
@MarioCastigliano there are no more issues – grazie!

2023-08-28 07:59 UTC, merged

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.tsx
> +      <Host>
Host element not needed

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.tsx
> +          {this._namedSlots['image'] && <slot name="image" />}
checking with namedSlots should not be needed and can be removed

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.tsx
> +          {this._namedSlots['legend'] && <slot name="legend" />}
checking with namedSlots should not be needed and can be removed

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.tsx
> +          {this._namedSlots['action'] && <slot name="action" />}
checking with namedSlots should not be needed and can be removed

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.stories.tsx
> +    },
nitpick, you could remove actions as its empty

2023-08-28 08:35 UTC, jeripeierSBB commented on src/components/sbb-no-results/sbb-no-results.scss
> +  @include sbb.legend;
nice!