feat(sbb-tab-group): tab titles redesign
lyne-design-system/lyne-components pull request #1975
Opened 2023-09-08 11:03 UTC by dauriamarco

Closes #1907

2023-09-08 15:27 UTC, DavideMininni-Fincons reviewed
I have to go deeper in code on Monday, however some notes:
- focus state in not drawn in Figma (now it's pretty squared)
- when pressed, title text should change position (as in the button)

I also noticed that the content panel can be focused and that a did-change event is triggered as soon as storybook loads the component, but it happens the same on master for both, so I assume it's ok.. :)

2023-09-13 04:59 UTC, mcilurzo commented
ux review: 
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj?node-id=27931:203205&mode=design#554101799
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj?node-id=27931:203199&mode=design#554103606

2023-09-18 10:23 UTC, dauriamarco commented
> I have to go deeper in code on Monday, however some notes:
> 
> * focus state in not drawn in Figma (now it's pretty squared)
> * when pressed, title text should change position (as in the button)
> 
> I also noticed that the content panel can be focused and that a did-change event is triggered as soon as storybook loads the component, but it happens the same on master for both, so I assume it's ok.. :)

Hi @DavideMininni-Fincons, thanks for the feedback. 
- The focus state should be present in [Figma](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=529-550879&mode=design&t=rUpmIIDFXJcc9wC5-0), it can be found by scrolling down a little and is indeed more squared off.
- I'm not sure if in the [prototype](https://www.figma.com/proto/9r6xSfNmEfCFxl1yFYedrj/branch/wGheg6gpTypsswasB0YvEI/Lyne-Components?type=design&page-id=459%3A502393&node-id=25974-493070&viewport=1288%2C-362%2C0.25&t=QU45eySZi0rqExCi-1&scaling=scale-down&starting-point-node-id=25974%3A493070) we still have the text shifting, I see a little movement but it seems more like a Figma's small glitch. In his UI review Manuel didn't comment on it, but we can ask for confirmation.

2023-09-18 12:18 UTC, dauriamarco commented
> ux review: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj?node-id=27931:203205&mode=design#554101799 https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj?node-id=27931:203199&mode=design#554103606

Hi @mcilurzo, thank you for the review. Here's the new link: https://lyne-components-preview-pr1975.app.sbb.ch/?path=/story/components-sbb-tab-sbb-tab-group--default-tabs-size-l

2023-09-21 16:03 UTC, DavideMininni-Fincons requested changes
Looks good, just something to check in stories.

2023-09-21 16:03 UTC, DavideMininni-Fincons commented on src/components/sbb-tab-group/sbb-tab-group.stories.tsx
>  const DefaultTemplate = (args): JSX.Element => (
Maybe change to `{size, ...args}`? Otherwise I think the size will be passed also in the `firstTabTitle` function

2023-09-21 16:03 UTC, DavideMininni-Fincons commented on src/components/sbb-tab-group/sbb-tab-group.stories.tsx
>  const DefaultTemplate = (args): JSX.Element => (
And same for other templates

2023-09-22 09:14 UTC, mcilurzo commented
@dauriamarco thank you for fixing the issues. everything is fine now.

2023-09-26 15:01 UTC, kyubisation approved these changes
Basically LGTM 👍 
One issue about the header underline

2023-09-28 11:37 UTC, kyubisation approved these changes
LGTM 👍 
Thanks! 😃

2023-09-28 12:35 UTC, DavideMininni-Fincons approved these changes
Looks good, thanks! :)

2023-09-28 12:36 UTC, merged