refactor(sbb-expansion-panel): improve expansion animation
lyne-design-system/lyne-components pull request #2043
Opened 2023-10-04 08:15 UTC by dauriamarco

Refactor `sbb-expansion-panel` animation.

2023-10-04 09:03 UTC, jeripeierSBB approved these changes
Love it! :)

2023-10-04 10:35 UTC, kyubisation approved these changes
LGTM 👍 
Nice work 😃

2023-10-04 10:46 UTC, jeripeierSBB requested changes

2023-10-04 10:46 UTC, jeripeierSBB commented on src/components/sbb-expansion-panel/sbb-expansion-panel.scss
>    --sbb-expansion-panel-animation-duration: var(--sbb-animation-duration-4x);
Please don't forget to remove [data-resize-disable-animation] in CSS

2023-10-05 07:47 UTC, dauriamarco commented
@jeripeierSBB I also checked that we had no problem with the content overflow as in the selection panel and we should be safe here. 👍

2023-10-09 07:44 UTC, jeripeierSBB approved these changes
LGTM

2023-10-09 07:44 UTC, merged