refactor(sbb-card): lit migration
lyne-design-system/lyne-components pull request #2056
Opened 2023-10-09 08:45 UTC by dauriamarco

Migrate `sbb-card`, `sbb-card-badge` and `sbb-card-action` to Lit.

2023-10-09 12:48 UTC, jeripeierSBB requested changes

2023-10-09 12:48 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
> +    document.querySelectorAll('button').forEach((el) => el.remove());
can we not reuse "buttons" const ?

2023-10-09 12:48 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
> +      const changeSpy = new EventSpy('click');
```suggestion
      const clickSpy = new EventSpy('click');
```

2023-10-09 12:48 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
> +      const changeSpy = new EventSpy('click');
```suggestion
      const clickSpy = new EventSpy('click');
```

2023-10-09 12:48 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
> +      const changeSpy = new EventSpy('click');
```suggestion
      const clickSpy = new EventSpy('click');
```

2023-10-09 12:48 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
> +      const changeSpy = new EventSpy('click');
```suggestion
      const clickSpy = new EventSpy('click');
```

2023-10-09 14:42 UTC, dauriamarco commented on src/components/sbb-card-action/sbb-card-action.tsx
> -    this._element.setAttribute('slot', 'action');
Unfortunately it was simply not working, so I had to move it

2023-10-09 14:43 UTC, dauriamarco commented on src/components/sbb-card-badge/sbb-card-badge.tsx
> -    // Set slot name as early as possible
Same here, it wasn't working and I had to move it

2023-10-09 15:01 UTC, dauriamarco commented on src/components/sbb-card/sbb-card.spec.ts
> -    expect(root).not.toHaveAttribute(hasBadgeDataAttributeName);
I thought this was an error, as the attribute remains on the host even for smaller sizes. I checked the behaviour of the current implementation on master, so I wonder why it now passes on master?

2023-10-10 07:21 UTC, TomMenga commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
Should we try to separate spec and e2e tests?
The effort and impact should be minimal.
@jeripeierSBB @dauriamarco what do you think?

2023-10-10 08:27 UTC, jeripeierSBB commented on src/components/sbb-card-action/sbb-card-action.e2e.ts
For me it doesn't matter. maybe we will once anyways merge the two files for every component :)

2023-10-10 08:28 UTC, jeripeierSBB approved these changes
LGTM, yay!

2023-10-10 08:46 UTC, merged