chore: update lit to 3.0
lyne-design-system/lyne-components pull request #2121
Opened 2023-10-27 14:37 UTC by TomMenga

### Known issues
- [ ] `@open-wc/lit-helpers` still has a dependency on lit 2.0 which causes the "Multiple version of lit..." warning

2023-10-31 15:44 UTC, jeripeierSBB reviewed
LGTM. can we not remove this.requestUpdate in setters now? -> https://lit.dev/blog/2023-10-10-lit-3.0/ 

> We now call requestUpdate() automatically for @property and @state decorated accessors where previously that was the setter's responsibility.

2023-10-31 16:05 UTC, TomMenga commented
> LGTM. can we not remove this.requestUpdate in setters now? -> https://lit.dev/blog/2023-10-10-lit-3.0/
> 
> > We now call requestUpdate() automatically for @Property and @State decorated accessors where previously that was the setter's responsibility.

I thought that we would need to do that once we started using standard decorators but you might have a point. I might have misinterpreted it.
We also need to move the `@property` and `@state` decorators from the getters to the setters.

I'll test if it's true that the 'request update' is called automatically now

2023-11-01 07:27 UTC, jeripeierSBB requested changes
A console log left and I suggest to use the following order: @property, setter, getter. I'ts more readable than getter, @property, setter.

2023-11-01 07:27 UTC, jeripeierSBB commented on src/components/sbb-accordion/sbb-accordion.tsx
> +  public override willUpdate(_changedProperties: Map<PropertyKey, unknown>): void {
probably left unintentionally

2023-11-01 09:05 UTC, merged