feat: implement initial support for SSR
lyne-design-system/lyne-components pull request #2437
Opened 2024-02-23 18:06 UTC by kyubisation

This is the initial implementation for SSR testing.

2024-02-26 10:29 UTC, jeripeierSBB requested changes
Thanks for starting this! I think some leftovers need to be handled.

Imports in [src/components/core/testing/a11y-tree-snapshot.ts](https://github.com/lyne-design-system/lyne-components/pull/2437/files#diff-016aa2786eca477f091d22b23ab3a99fded63a6c497b34fb2b4315f8b37b5a76) have to be fixed

2024-02-26 10:29 UTC, jeripeierSBB requested changes
Thanks for starting this! I think some leftovers need to be handled.

Imports in [src/components/core/testing/a11y-tree-snapshot.ts](https://github.com/lyne-design-system/lyne-components/pull/2437/files#diff-016aa2786eca477f091d22b23ab3a99fded63a6c497b34fb2b4315f8b37b5a76) have to be fixed

2024-02-26 11:38 UTC, kyubisation commented on src/components/accordion/accordion.e2e.ts
> +    await element.updateComplete;
I wanted to check, whether that would be enough. I will revert it.

2024-02-26 11:43 UTC, kyubisation commented on web-test-runner.config.js
> +    //{ name: 'spec', files: 'src/**/*.spec.ts' },
I want to discuss this during refinement, as it has consequences.

2024-02-28 11:38 UTC, jeripeierSBB commented on web-test-runner.config.js
> +    <meta name="testEnvironment" ${isDebugMode ? 'debug' : ''}>
Should html data- attributes be used?

2024-02-28 11:55 UTC, jeripeierSBB commented on src/components/icon/icon-base.ts
> +    if (!this.hasAttribute('data-empty')) {
Fix this

2024-02-28 12:06 UTC, jeripeierSBB commented on web-test-runner.config.js
> -  coverageConfig: {
Fix Coverage

2024-02-28 15:09 UTC, kyubisation commented on web-test-runner.config.js
> +    <meta name="testEnvironment" ${isDebugMode ? 'debug' : ''}>
Will be considered in a separate PR.

2024-02-28 15:37 UTC, merged